module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './',
  modulePaths: ['./'],
  testRegex: '.e2e-spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '/dist/',
    '/lib/',
    '/coverage/',
    '/deployment/',
    '/scripts/',
    '/logs/',
    '.module.ts',
    '.dto.ts',
    '.entity.ts',
    '.enum.ts',
    '.interface.ts',
    '.constant.ts',
    '/src/global/',
    'main.ts',
  ],
  testTimeout: 10000,
};
