services:
  app:
    restart: ${CONTAINER_RESTART}
    container_name: ${APP_NAME}
    image: ${APP_NAME}:${APP_VERSION}
    build: .
    volumes:
      - ./logs:/home/app/backend/logs
      - .env:/home/app/backend/.env
    ports:
      - '${CONTAINER_PORT}:3000'
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
    tty: true
    stdin_open: true

  db:
    restart: ${CONTAINER_RESTART}
    container_name: ${APP_NAME}-db
    image: postgres:15
    hostname: ${POSTGRES_HOST}
    environment:
      - TZ=Asia/Taipei
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env

volumes:
  db-volume:
    external: false
    name: ${APP_NAME}-db-volume

networks:
  app-network:
    name: ${APP_NAME}-network
    driver: bridge
