FROM node:20

RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app/backend
RUN mkdir -p $HOME
WORKDIR $HOME

# COPY 所有原始碼，除了 .dockerignore 的資料夾外
COPY . .

RUN npm install -g typescript 
RUN npm install

RUN npm run build

RUN chown -R app:app $HOME/dist

RUN rm -rf $HOME/src
RUN npm install --production

USER app
CMD ["node", "dist/main.js"]
